### ISSUE TITLE
patch_size设置相关问题

### ISSUE THREAD

**Issue by Turnsole1** [passerer/RFDN#1]
patch_size设置为256的话，超分结果会不正常；设置为128则正常。此外，我测试了一些其他的数值，发现patch_size设置的小超分结果都正常，设置偏大超分结果就不正常。请问您有遇到过这种情况吗？或者麻烦您解释一下其中原因。

**Comment by passerer** [comment]
请检查训练数据中的HR的分辨率是否都大于256x256

**Comment by Turnsole1** [comment]
> 请检查训练数据中的HR的分辨率是否都大于256x256

非常感谢您及时的回复。我使用的是DIV2K训练集，我一会回去检查一下，但是感觉应该都是超过256*256的。

**Comment by Turnsole1** [comment]
刚看了一下，DIV2K中都是高清大图，分辨率都比256*256要大。

**Comment by passerer** [comment]
超分结果不正常是指？
1：训练loss异常
2：训练loss正常但验证集的PSNR异常

**Comment by Turnsole1** [comment]
训练loss正常，下降很快，4个epoch后loss基本就下降到0.01+；
训练时没有测PSNR，我一会测一下；
图片超分结果如下图所示：



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月30日(周四) 上午8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1)




 
超分结果不正常是指？
 1：训练loss异常
 2：训练loss正常但验证集的PSNR异常

**Comment by Turnsole1** [comment]
> 超分结果不正常是指？
> 1：训练loss异常
> 2：训练loss正常但验证集的PSNR异常

因为这里不方便拍照，已在邮箱回复您

**Comment by passerer** [comment]
似乎没看到图片



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 上午9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1)





 训练loss正常，下降很快，4个epoch后loss基本就下降到0.01+； 
 训练时没有测PSNR，我一会测一下； 
 图片超分结果如下图所示： 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年6月30日(周四) 上午8:54 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1) 
 
 
 
 
   
 超分结果不正常是指？ 
  1：训练loss异常 
  2：训练loss正常但验证集的PSNR异常

**Comment by Turnsole1** [comment]
图片在刚才那个邮件的附件里，可以看到吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月30日(周四) 上午9:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1)




 似乎没看到图片 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年6月30日(星期四) 上午9:14 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1) 
 
 
 
 
 
  训练loss正常，下降很快，4个epoch后loss基本就下降到0.01+；  
  训练时没有测PSNR，我一会测一下；  
  图片超分结果如下图所示：  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年6月30日(周四) 上午8:54  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1)  
   
   
   
   
     
  超分结果不正常是指？  
   1：训练loss异常  
   2：训练loss正常但验证集的PSNR异常

**Comment by passerer** [comment]
没有发现附件。这是我的邮箱：chencha0@foxmail.com 可以直接通过这个沟通

**Comment by Turnsole1** [comment]
patch_size为256时进行测试，测试时PSNR为8，SSIM为0.05；但是训练时PSNR、SSIM和loss都正常。

**Comment by Turnsole1** [comment]
好的，多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月30日(周四) 上午9:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [passerer/RFDN] patch_size设置相关问题 (Issue #1)




 
***@***.*** 可以直接通过这个沟通

**Comment by Turnsole1** [comment]
今天又做了一些实验，发现训练时无论patch_size设置为多少，在测试时都有可能出现超分结果不正常的现象。

**Comment by Turnsole1** [comment]
初步判断可能是由于模型自动初始化造成的。

**Comment by Turnsole1** [comment]
解决了，原来是这个问题：https://cloud.tencent.com/developer/article/1725372
谢谢啦～
