### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by Yzs007** [passerer/RFDN#2]
哈喽，我想问一下你这个是复现论文的程序吗？如果是的话你得出的结果和原论文一致吗？

**Comment by passerer** [comment]
你好，可以复现相似的结果。

**Comment by Yzs007** [comment]
你的pytorch和numpy、python版本是什么呢？可以跟我说一下嘛，因为我运行的时候报错了。

**Comment by passerer** [comment]
python==3.6
numpy==1.18.5
torch==1.10.1

**Comment by Yzs007** [comment]
您好，我还想请教一下一个问题。就是在论文中用来对比的那些算法全都要自己跑一遍吗？ 还是用原作者得出的指标（PSNR/SSIM）和原作者的预训练模型？因为自己跑感觉得不出和原来一样的指标

**Comment by passerer** [comment]
> 您好，我还想请教一下一个问题。就是在论文中用来对比的那些算法全都要自己跑一遍吗？ 还是用原作者得出的指标（PSNR/SSIM）和原作者的预训练模型？因为自己跑感觉得不出和原来一样的指标

如果是写论文的话，建议直接引用原作者的指标。由于随机因素的影响，自己跑的带的结果可能和原作者报告的指标有差异

**Comment by Yzs007** [comment]
> 

好的，非常感谢您的解答，因为我自己捣鼓有太多疑惑了

**Comment by LiYufengzz** [comment]
你好，请问rgb_range为什么设成1而不是255呢？我看edsr设的是255
